### ISSUE TITLE
PyPi release?

### ISSUE THREAD

**Issue by jramapuram** [dccastro/Morpho-MNIST#2]
Great stuff with Morpho-MNIST! Any chance of a pypi release for easy packaging?

**Comment by dccastro** [comment]
Hi @jramapuram, thanks a lot for the interest and sorry for the much delayed reply! I'd hesitate to release this codebase on PyPI without a lot more work on testing and documentation, and unfortunately at the moment I don't have much time to maintain this repository by myself.

**Comment by jramapuram** [comment]
No worries @dccastro ! Understandable. Can you add a LICENSE.md file so that folks that have some time can handle this?

**Comment by dccastro** [comment]
Thanks for the suggestion, @jramapuram. I've now added an MIT licence for this repository.
